config/routes.rb
Rails.application.routes.draw do
    
    root 'static_pages#home'
    #match '/about',     to: 'static_pages#about',   via: 'get'
    get 'about' => 'static_pages#about'
    
    resources :users,       only: [:new, :create, :show, :index]
    #match '/signup',    to: 'users#new',            via: 'get'
    get 'signup' => 'users#new'
    
    resources :sessions,    only: [:new, :create, :destroy]
    #match '/signin',    to: 'sessions#new',         via: 'get'
    #match '/signin',    to: 'sessions#create',      via: 'post'
    #match '/signout',   to: 'sessions#destroy',     via: 'delete'
    get 'signin'        => 'sessions#new'
    post 'signin'       => 'sessions#create'
    delete 'signout'    => 'sessions#destroy'
    
    resources :events,      only: [:new, :create, :show, :index]
    
    resources :invites,     only: [:create, :destroy]
end

app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :creator, :class_name => "User"
    
    has_many :invites, :foreign_key => "attended_event_id"
    has_many :attendees, :through => :invites
    
    scope :upcoming, -> { where("Date >= ?", Date.today).order('Date ASC') }
    scope :past, -> { where("Date < ?", Date.today).order('Date DESC') }
end

app/models/invite.rb
class Invite < ActiveRecord::Base
    belongs_to :attendee, class_name: "User"
    belongs_to :attended_event, class_name: "Event"
    
    validates :attendee_id, presence: true
    validates :attended_event_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :events, :foreign_key => :creator_id
    
    has_many :invites, :foreign_key => :attendee_id
    has_many :attended_events, :through => :invites
    
    before_create :create_remember_token
    
    def upcoming_events
        self.attended_events.upcoming
    end
    
    def previous_events
        self.attended_events.past
    end
    
    def User.new_remember_token
        SecureRandom.urlsafe_base64
    end
    
    def User.digest(token)
        Digest::SHA1.hexdigest(token.to_s)
    end
    
    def attending?(event)
        event.attendees.include?(self)
    end
    
    def attend!(event)
        self.invites.create!(attended_event_id: event.id)
    end
    
    def cancel!(event)
       self.invites.find_by(attended_event_id: event.id).destroy 
    end
    
    private
    
    def create_remember_token
        self.remember_token = User.digest(User.new_remember_token)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
      @event = current_user.events.build
  end

  def create
      @event = current_user.events.build(event_params)
      if @event.save
          redirect_to event_path(@event)
      else 
          render 'new'
      end
  end

  def show
      @event = Event.find(params[:id])
  end

  def index
      @events_upcoming = Event.upcoming.paginate(page: params[:upcoming])
      @events_past = Event.past.paginate(page: params[:past])
  end
  
  private
  
  def event_params
      params.require(:event).permit(:title, :location, :description, :date)
  end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def create
      @event = Event.find(params[:invite][:attended_event_id])
      current_user.attend!(@event)
      redirect_to @event
  end

  def destroy
      @event = Invite.find(params[:id]).attended_event
      current_user.cancel!(@event)
      redirect_to @event
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user
        signin user
        redirect_back_or user
      else
        flash.now[:error]="You're not registered, please sign up"
        render 'new'
      end
  end
  
  def destroy
      signout
      redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
      if signed_in?
          @user = current_user
          @previous_events = @user.previous_events
          @upcoming_events = @user.upcoming_events
      end
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
          signin @user
          redirect_to @user
      else
          render 'new'
      end
  end

  def show
      @user = User.find(params[:id])
      @previous_events = @user.previous_events
      @upcoming_events = @user.upcoming_events
  end
  
  def index
      @users = User.paginate(page: params[:page])
  end
  
  private
  
  def user_params
      params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def nav_link(link_text, link_path)
        class_name = current_page?(link_path) ? 'active' : nil
        
        content_tag(:li, :class => class_name) do
            link_to link_text, link_path
        end
    end
end

app/helpers/events_helper.rb
module EventsHelper
    def host?(user)
        current_user == user
    end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def signin(user)
        remember_token = User.new_remember_token
        cookies.permanent[:remember_token] = remember_token
        user.update_attribute(:remember_token, User.digest(remember_token))
        self.current_user = user
    end
    
    def current_user=(user)
        @current_user = user
    end
    
    def current_user
        remember_token = User.digest(cookies[:remember_token])
        @current_user ||= User.find_by(remember_token: remember_token)
    end
    
    def signed_in?
        !current_user.nil?
    end
    
    def signout
        current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
        cookies.delete(:remember_token)
        self.current_user = nil
    end
    
    def current_user?(user)
        user == current_user
    end
    
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end
    
    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_attend.html.erb
<%= form_for(current_user.invites.build(attended_event_id: @event.id) ) do |f| %>
    <div><%= f.hidden_field :attended_event_id %></div>
    <%= f.submit "Attend", class: "btn btn-lg btn-primary" %>
<% end %>

app/views/events/_attend_form.html.erb
<div id = "attend_form">
    <% if current_user.attending?(@event) %>
        <%= render 'cancel' %>
    <% else %>
        <%= render 'attend' %>
    <% end %>
</div>

app/views/events/_cancel.html.erb
<%= form_for(current_user.invites.find_by(attended_event_id: @event.id), html: { method: :delete }) do |f| %>
    <%= f.submit "Cancel", class: "btn btn-lg" %>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1>Browse All Events</h1>

<h2>Upcomings</h2>
<%= render 'shared/table', object: @events_upcoming %>
<%= will_paginate @events_upcoming, :param_name => "upcoming" %>

<h2>Past</h2>
<%= render 'shared/table', object: @events_past %>
<%= will_paginate @events_past, :param_name => "past" %>

app/views/events/new.html.erb
<h1>Create Event</h1>

<div class = "row">
    <div class = "col-md-6 col-md-offset-3">
        <%= form_for(@event) do |f| %>
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>
            
            <%= f.label :location %>
            <%= f.text_field :location, class: "form-control" %>
            
            <%= f.label :description %>
            <%= f.text_area :description, class: "form-control" %>
            
            <%= f.label :date %>
            <%= f.date_field :date, class: "form-control"  %>
            
            <%= f.submit "Create Event", class: "btn btn-lg btn-primary" %>
        <% end %>
    </div>
</div>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<% if signed_in? %>
    <div class = "text-center"><%= render 'attend_form' %></div>
<% end %>

<p><b>location: </b><%= @event.location %></p>
<p><b>host: </b><%= @event.creator.name %></p>

<p><%= @event.description %></p>

</br>

<b>Who's Going:</b>

<ol>
<% @event.attendees.each do |attendee| %>
    <li><%= link_to attendee.name, attendee %></li>
<% end %>
</ol>
    
    
    

app/views/invites/create.html.erb
<h1>Invites#create</h1>
<p>Find me in app/views/invites/create.html.erb</p>

app/views/invites/destroy.html.erb
<h1>Invites#destroy</h1>
<p>Find me in app/views/invites/destroy.html.erb</p>

app/views/layouts/_header.html.erb
<div class="header">
    <ul class="nav nav-pills pull-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Events", events_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "About", about_path%></li>
        
        <% if signed_in? %>
            <li><%= link_to "#{current_user.name} (Sign Out)", signout_path, method: "delete" %></li>
        <% else %> 
            <li><%= link_to "Sign In", signin_path %></li>
        <% end %>
        
    </ul>
    <h3 class = "text-muted">Private EventBrite</h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
        <%= render 'layouts/header' %>
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/shared/_table.html.erb
<table class = "table table-condesed">
    <thead>
        <tr>
            <td class = "col-sm-2">Date</td>
            <td class = "col-sm-4">Title</td>
            <td class = "col-sm-3">Location</td>
            <td class = "col-sm-2">Host</td>
            <td class = "col-sm-1">Attend</td>
        </tr>
    </thead>
    
    <% object.each do |event| %>
    <tr>
        <td><%= event.date %></td>
        <td><%= link_to event.title, event_path(event) %></td>
        <td><%= event.location %></td>
        <td><%= link_to event.creator.name, user_path(event.creator) %></td>
        <td class = "text-center"><%= link_to event.attendees.count, event_path(event) %></td>
    </tr>
    <% end %>
</table>

app/views/shared/_user_home.html.erb
<h1>Welcome, <%= @user.name %>
<small><%= @user.email %></small></h1>

<div class = "text-center">
    <%= link_to "Create New Event", new_event_path, class: "btn btn-lg btn-success" %>
</div>

<% if @upcoming_events.any? %>
<h2>Upcoming:</h2>
<%= render 'shared/table', object: @upcoming_events %>
<% end %>

<% if @previous_events.any? %>
<h2>You Attended:</h2>
<%= render 'shared/table', object: @past_events %>
<% end %>

<% if @user.events.any? %>
<h2>Your Created Event:</h2>
<%= render 'shared/table', object: @user.events %>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>This project is being build as part of <strong>The Odin Project</strong> tutorial 
to build a site similar to a private Eventbrite which allows users to create events and then manage user signups. </p>

app/views/static_pages/home.html.erb
<% if signed_in? %>

    <%= render 'shared/user_home' %>
    
<% else %> 

    <div class="jumbotron">
        <h1> Plan an Event </h1>
        <p class="lead">Keep track of events with your friends. This is a simple app to organize your event planning. </p>
        <p> <%= link_to "Create an Event", signup_path, class: "btn btn-lg btn-success" %> </p>
    </div>
        
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<div class = pagination-wrapper>
    <%= will_paginate %>
</div>

<ul class = "users" >
    <% @users.each do |user| %>
        <li><%= link_to user.name, user %></li>    
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<div class = "row">
    <div class = "col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
            
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control" %>
        
            <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
  
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>
<small><%= @user.email %></small></h1>

<% if current_user?(@user) %>
    <div class = "text-center">
        <%= link_to "Create New Event", new_event_path, class: "btn btn-lg btn-success" %>
    </div>
<% end %>

<% if @upcoming_events.any? %>
    <h2>Upcoming: </h2>
    <%= render 'shared/table', object: @upcoming_events %>
<% end %>

<% if @previous_events.any? %>
    <h2>Attended: </h2>
    <%= render 'shared/table', object: @past_events %>
<% end %>

<% if @user.events.any? %>
    <h2>Created by <%= @user.name %> </h2>
    <%= render 'shared/table', object: @user.events %>
<% end %>